from tkinter import *
from tkinter import ttk

root = Tk()
frm = ttk.Frame(root, padding=10)
frm.grid()
ttk.Label(frm, text="buceta").grid(column=0, row=0)
ttk.Button(frm, text="0", command=lambda: print(0)).grid(column=2, row=3)
ttk.Button(frm, text="1", command=lambda: print(1)).grid(column=1, row=2)
ttk.Button(frm, text="2", command=lambda: print(2)).grid(column=2, row=2)
ttk.Button(frm, text="3", command=lambda: print(3)).grid(column=3, row=2)
ttk.Button(frm, text="4", command=lambda: print(4)).grid(column=1, row=1)
ttk.Button(frm, text="5", command=lambda: print(5)).grid(column=2, row=1)
ttk.Button(frm, text="6", command=lambda: print(6)).grid(column=3, row=1)
ttk.Button(frm, text="7", command=lambda: print(7)).grid(column=1, row=0)
ttk.Button(frm, text="8", command=lambda: print(8)).grid(column=2, row=0)
ttk.Button(frm, text="9", command=lambda: print(9)).grid(column=3, row=0)
root.bind(0, lambda event: print(event.keysym))
root.bind(1, lambda event: print(event.keysym))
root.bind(2, lambda event: print(event.keysym))
root.bind(3, lambda event: print(event.keysym))
root.bind(4, lambda event: print(event.keysym))
root.bind(5, lambda event: print(event.keysym))
root.bind(6, lambda event: print(event.keysym))
root.bind(7, lambda event: print(event.keysym))
root.bind(8, lambda event: print(event.keysym))
root.bind(9, lambda event: print(event.keysym))
root.mainloop()

